name: gravatar_utils
description: A library to generate Gravatar URLs.
version: 1.0.0
homepage: https://github.com/WebTrit/gravatar_utils

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
